### ISSUE TITLE
Fix c++11 warnings related to constant string conversion

### ISSUE THREAD

**Issue by HoracioDos** [lxi-tools/lxi-tools#15]
hello
I've been upgrading some machines to LM19 this week. As qtcharts is available now in 18.04 I compiled lxi-gui for i386. It works fine but there are some warnings about converting a string constant to ‘char*’ if you want to look at them.
[Compile Warnings.txt](https://github.com/lxi-tools/lxi-tools/files/2254362/Compile.Warnings.txt)

**Comment by lundmar** [comment]
Thanks. Fixed in 6fcbaaaced58731565ae2d32b977e8719fb57eba
