### ISSUE TITLE
liblxi not found even though it's installed

### ISSUE THREAD

**Issue by nonchip** [lxi-tools/lxi-tools#25]
I built & installed liblxi (from the 1.13 tarball; to /usr/local/lib, which is in my ld.so.conf), but when I run `configure` on lxi-tools (from the 1.21 tarball) I get:

    checking for lxi_connect in -llxi... no
    configure: error: liblxi not found

the linker setup definitely worked though:

    $ ldconfig -p | grep lxi
         liblxi.so.1 (libc6,x86-64) => /usr/local/lib/liblxi.so.1
            liblxi.so (libc6,x86-64) => /usr/local/lib/liblxi.so

so i wonder if `configure` could be trying to override `LD_{LIBRARY,RUN}_PATH` or trying to somehow find the library using some heuristic that's excluding `/usr/local` even though it's a pretty standard path...

there also doesn't seem to be a `--with-lxi=path` parameter for it?
even `LDFLAGS=' -L/usr/local/lib ' ./configure` doesn't work.

EDIT: `configure.log` shows:

    configure:12385: checking for lxi_connect in -llxi
    configure:12410: gcc -o conftest -g -O2   conftest.c -llxi  -lreadline  >&5
    /bin/ld: /usr/local/lib/liblxi.so: undefined reference to `avahi_discover'
    collect2: error: ld returned 1 exit status

sooo i guess there's a check missing in liblxi's configure and the `ld` error is misinterpreted as a generic "library not found"?

my package manager says:

    $ xbps-query -s avahi
    [*] avahi-0.7_8                   Multicast DNS Service Discovery
    [*] avahi-compat-libs-0.7_8       Avahi compatiblity shared libraries
    [*] avahi-compat-libs-devel-0.7_8 Avahi compat libraries - development files
    [*] avahi-discover-0.7_8          Service discover user interface for avahi
    [*] avahi-glib-libs-0.7_8         Avahi glib shared libraries
    [*] avahi-glib-libs-devel-0.7_8   Avahi glib libraries - development files
    [*] avahi-libs-0.7_8              Avahi shared libraries
    [*] avahi-libs-32bit-0.7_8        Avahi shared libraries (32bit)
    [*] avahi-libs-devel-0.7_8        Avahi core libraries - development files
    [*] avahi-python-0.7_8            Python utility package for Avahi
    [*] avahi-ui-libs-gtk3-0.7_8      Avahi UI GTK+3 shared libraries

soooo pretty sure that's all there, and i don't even find anything related to `avahi_discover` as a library export on google, just the `avahi-discover` cli tool. plus liblxi's readme claims avahi to be optional.

**Comment by lornix** [comment]
Be sure to tell 'configure' where the libraries are located.  /lusr/local/lib is a non-default path.

./configure --libdir=/usr/local/lib

--OR--

LDFLAGS=-L/usr/local/lib ./configure

First method is easier.  Basically, linker can see the library (ldconfig -p example), but 'configure' is kinky and wants to *touch* it to verify it exists.

**Comment by lundmar** [comment]
Seems you have the liblxi library file but for some reason it does not contain the lxi_init function.

Anyway, a lot of changes are coming, including switching from autotools to meson so you may get a better experience on your distribution soon.

**Comment by dwarning** [comment]
Sorry to re-open this issue.
I tried to build from source on Ubuntu 20.04 and got this:
`Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency readline found: YES 8.0
Run-time dependency lua-5.3 found: YES 5.3.3
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency liblxi found: NO (tried pkgconfig and cmake)

src/meson.build:42:0: ERROR: Dependency "liblxi" not found, tried pkgconfig and cmake
`
liblxi and liblxi-dev is installed but:
`dietmar@modsys:~/Projects/lxi-tools$ pkg-config --modversion liblxi
Package liblxi was not found in the pkg-config search path.
Perhaps you should add the directory containing `liblxi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'liblxi' found
`
Seems the installation is not complete. Should I install liblxi from source?

**Comment by lundmar** [comment]
You are a bit too early - this is an issue of non-released lxi-tools and liblxi.

We've recently migrated to meson and that primarily rely on pkgconfig for resolving library configurations etc. The old liblxi using autotools does not install a pkgconfig. The latest git versions, liblxi installs a pkgconfig configuration so that lxi-tools can find it.

In, in short, install the latest git version of liblxi and it will match.

**Comment by dwarning** [comment]
OK, I will wait.
Thank you for the nice work.

**Comment by lundmar** [comment]
No problem. It will be released soon. Until then you could try out the edge snap for easy install.

**Comment by dwarning** [comment]
I tried snap - but I got
`dietmar@modsys:~$ lxi-gui
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Qt: Session management error: Could not open network socket
`
libatk-adaptor libgail-common was installed properly.

lxi-gui seems functiona, but in the end I removed the snap.

**Comment by lundmar** [comment]
Since lxi-tools v2.0 has not yet been officially released you need to install the bleeding edge snap like so:

`$ snap install lxi-tools --edge`

**Comment by nonchip** [comment]
gotta love the necromancy spam...
