### ISSUE TITLE
Device not found: LDH400

### ISSUE THREAD

**Issue by fantilator** [lxi-tools/lxi-tools#26]
Hi, I have a LDH400 DC load with LXI enabled, still the tools are unable to find the device.

I have tried all mDNS services. 
The linux is running on a VM in the same network as the DC load.
trying the command line give ma also an error.

Can you help me out where it gets stuck?
Kind Regards
Davy

![cmdline](https://user-images.githubusercontent.com/23620190/65168287-78278d00-da44-11e9-9f36-370939ae0fb4.png)

Please find attached some screenshots.
![LDH400](https://user-images.githubusercontent.com/23620190/65168134-2f6fd400-da44-11e9-801a-935f353358da.png)
![wireshark](https://user-images.githubusercontent.com/23620190/65168136-2f6fd400-da44-11e9-8ba2-f54d003a2f68.png)

EDIT: When rinning the command  with -r and specific port it works.
I cannot change the port number.
Is it possible to add the feature in the GUI? 

![cmdline2](https://user-images.githubusercontent.com/23620190/65168729-68f50f00-da45-11e9-962a-2ddd49430f70.png)

**Comment by jstiefel** [comment]
Same problem with the Aim TTi CPX400SP. Connected it to a local switch with a fixed IP and I can ping it, go to the web interface etc.

> EDIT: When rinning the command with -r and specific port it works.
> I cannot change the port number.

This solved it, although I don't understand why a search via mDNS is necessary if I use an IP.

**Comment by lundmar** [comment]
To me it seems like your Aim instruments do not support the standard VXI11 protocol but only RAW TCP for sending commands.

**Comment by lundmar** [comment]
> This solved it, although I don't understand why a search via mDNS is necessary if I use an IP.
Apparently your instrument does not support the old way of discovery that most instruments support. Maybe Aim decided to leave it behind.

**Comment by lundmar** [comment]
> EDIT: When rinning the command with -r and specific port it works. I cannot change the port number. Is it possible to add the feature in the GUI?

The lxi-gui application has recently been fully rewritten in GTK4. I may add such option in the future but the gui is really only meant to be simple and support instruments which adhere strictly to the LXI standard.

**Comment by lundmar** [comment]
Oh, by the way. If you guys run stuff in a VM, you have to remember to bridge the VM network with your local network else the discovery broadcast messages will be lost. This may be another reason the discover feature did not work for you.
