### ISSUE TITLE
DS1202Ze - most SCPI commands do not work

### ISSUE THREAD

**Issue by grindhold** [lxi-tools/lxi-tools#27]
hi! i am trying to use lxi-tools on my DS1202Ze and the only commands that seem to work are ":RUN" ":STOP" and "*IDN?".
even ":AUTO" simply leads to no reaction on the site of the oscilloscope
any command that testes which is supposed to yield a result (ends in '?') ends up with a timeout. I tested e.g. ":KEY:LOCK?" ":BEEP:ENAB?"
am i missing something on the side of the scope?
the programmers manual of the scope just talks about usb, rs232 and gbip, but not about lxi which baffles me.

however sceenshot acquisition works flawlessly.

P.S.: really  a nice tool so far. getting a screenshot with  just one command and no configuration was an awesome out-of-the-box experience!

**Comment by lundmar** [comment]
Hi. I'm glad you had a good out of the box experience with the screenshot feature.

The SCPI command feature seems to be working fine too. The only problem is that you are firing commands that your instrument does not support. For example, to lock the keyboard you would have to fire ":SYSTem:LOCKed". Likewise to query the lock status you fire ":SYSTem:LOCKed?".

Please take care to read the programming manual of your instrument.
