### ISSUE TITLE
lxi-tools-gui crash when trying to make screenshot or liveview, SIGLENT SDS2104X

### ISSUE THREAD

**Issue by Knudch** [lxi-tools/lxi-tools#31]
Taking a screenshot from sds2104x oscilloscope makes the lxitools-gui crash, doing it from console to a file works fine.
Screenshot or live capture from a sdm3065x (multimeter) works fine.

System: Fedora F34, lxi-tools 1.21-5.fc24 fedora repos
correction: lxi-tools installed via snap

**Comment by lundmar** [comment]
Could be a bug in lxi-gui.

However, lxi-gui has been fully rewritten in GTK4. It may work better. It will be available in the next release.
