### ISSUE TITLE
GUI: Manually specify targets?

### ISSUE THREAD

**Issue by stromnet** [lxi-tools/lxi-tools#35]
Is it possible to manually specify IP to connect to?
I cannot use Search since devices are on another broadcast domain.

Cannot find anything in docs or UI, but it wouldn't be the first time some GUI is messed up in my WM (sway), so I might be missing something that should be obvious..
Thanks!

**Comment by lundmar** [comment]
Sorry. Right now it does not support adding devices manually. However, it will be added in the future but only after v2.0 has been released.

**Comment by lundmar** [comment]
Support for manually adding instruments is now supported. Added in f243363fafd273d966d1ef22a373352432584717 and will be part of the next release.
