### ISSUE TITLE
Missing transcript window controls

### ISSUE THREAD

**Issue by hooperbloob** [lxi-tools/lxi-tools#40]
The instrument listings on the left have a context menu for copying things but there isn't one for the transcript window.

Suggested:

   Select all
   Save to...
   Clear
   Copy to clipboard

**Comment by lundmar** [comment]
There is a standard context menu which includes "Select all", "Copy", etc.

But yes it does not include "Save to.." or "Clear all". I will implement those.

**Comment by lundmar** [comment]
95fa79315f849ba7767dcc0c4f2bb4ae4a3fbf65 adds "Clear all" and "Save as.." to the SCPI text view context menu.
