### ISSUE TITLE
No readline.pc in readline 6.2 and 7

### ISSUE THREAD

**Issue by robert-scheck** [lxi-tools/lxi-tools#47]
Unfortunately, there is no `readline.pc` file for pkg-config in readline 6.2 and 7.0 (it doesn't seem to be a Fedora/RHEL-specific packaging problem, because Debian Stretch and Buster have exactly the same issue). Given the before mentioned readline versions are part of RHEL 7 and 8, lxi-tools 2.x (the command-line variant) can't be build anymore.

**Comment by lundmar** [comment]
Right. Fixed in d55f9393388aff4b0c63b20f668c451e6c998465

**Comment by lundmar** [comment]
Hopefully one day most/all libraries will carry a pkg-config.

**Comment by robert-scheck** [comment]
Confirming, commit d55f9393388aff4b0c63b20f668c451e6c998465 builds on all active Fedora and RHEL releases on all architectures.
