### ISSUE TITLE
Tested/working report

### ISSUE THREAD

**Issue by bombsquad81** [lxi-tools/lxi-tools#62]
Working well with Siglent,SDS1152CML+ firmware v6.01.01.22 over VXI11/TCP.
Screenshots, SCPI and discovery all work.

liblxi 1.18 / lxi-tools 2.4

Thanks for all your work; now I can monitor pass/fail testing in the workshop... from my sofa :)

**Comment by lundmar** [comment]
Thank you. I'm happy to hear you find liblxi/lxi-tools useful.

I've added your instrument to our list of tested instruments.

Keep rocking that sofa! ;)
