### ISSUE TITLE
report Rohde&Schwarz RTH 1004

### ISSUE THREAD

**Issue by JanSchmidt3** [lxi-tools/lxi-tools#66]
Hi,

I tested RS oscilloscope. 
- scpi seems to work

lxi scpi "*IDN?" -a 10.85.100.39
Rohde&Schwarz,RTH,1317.5000k04/105749,1.80.3.4

- discover I cannot test (because I run lxi from docker with a different ip address)
- screenshot does not work

root@c7059b1f899a:/# lxi screenshot -a 10.85.100.39
Loaded rs-hmo-rtb screenshot plugin
Error: Read error (timeout)
Error: Failed to receive message

I run wireshark. lxi asks for "HCOPy:DATA?", but the scope does not answer.

**Comment by lundmar** [comment]
Kind of same issue as for the Tektronix scope - a new plugin is required to handle this scope.

Taking a screenshot is a bit more involved than a simple "HCOPy:DATA?" command. According to the example in the users manual an intermediate file is required and perhaps even and SD card for storage:

```
:HCOPy:LANGuage PNG
:MMEMory:NAME '/media/SD/Screenshot.png'
:HCOPy:IMMediate;*OPC
:MMEMory:DATA? '/media/SD/Screenshot.png'
:MMEMory:DELete '/media/SD/Screenshot.png';*OPC
```

If you can help confirm that these are the commands needed to be fired to retrieve the screenshot data then I can help write the plugins.

**Comment by JanSchmidt3** [comment]
your proposal worked. I could save the screenshot to the Scopes memory. Transmitting to the host was also possible. But the resulting file could not be displayed.

The file starts with
00000000  23 35 34 36 30 33 35 89  50 4e 47 0d 0a 1a 0a 00  |#546035.PNG.....|
00000010  00 00 0d 49 48 44 52 00  00 03 20 00 00 01 e0 08  |...IHDR... .....|

after removing the first 7 bytes (via dd) the file could be displayed.

The last command deletes the file again, so the memory gets cleaned.

Maybe it is useful to invert the colors before start the screenshot (or as an option).

":HCOPy:INVerse ON"
