### ISSUE TITLE
Feature request: Rigol MSO4000 Series

### ISSUE THREAD

**Issue by MarkSupp** [lxi-tools/lxi-tools#69]
Would it be possible to add the Rigol MSO4000 Series to the list of supported devices? Currently, it's only possible to receive the identifier but no screen dump. I'm willing to help with testing and I am able to provide documentation if needed.
Thanks in Advance!

**Comment by lundmar** [comment]
Hi @MarkSupp I've looked at the programmers manual for Rigol MSO4000 and it looks like we can reuse the rigol-2000 screenshot plugin.

You can test it by selecting the plugin manually.

I've made a change so it should automatically detect and select the right plugin. It will soon be available on the snap edge channel.

**Comment by MarkSupp** [comment]
Thank you very much, I am eager to try it out!

**Comment by MarkSupp** [comment]
I'm passing along the requests of my father, since he is not used to working with GitHub:
Not tested yet - waiting for latest Snap Edge version for it.
My systems are MSO4024 and MSO4054.
You could extend the plugin also to the DS4000 series - they are the same, despite the logic probe.

**Comment by lundmar** [comment]
Thanks. Let me know if they work then I will update the list of supported instruments.

I'll extend the plugin to work with DS4000 also.

**Comment by MarkSupp** [comment]
Latest Snap Edge showed up at my Ubuntu - it works like a charm. Thank you so much for your ultra-fast response.
![image_2023-03-06_14-23-17](https://user-images.githubusercontent.com/75885667/223122723-6b98b210-9dea-4903-ae35-4275541618fc.png)

**Comment by lundmar** [comment]
Great. Thanks for reporting and testing. I hope you find lxi-tools useful.

I've added the two models to the list of supported instruments.

**Comment by MarkSupp** [comment]
Hi,
There seems to be a Problem with the Lua script not recognizing certain keywords/commands. Do you possibly have an idea why this might be happening? Some commands (print, tonumber) seem to work while others (connect, msleep, scpi) do not.

**Comment by lundmar** [comment]
Yes, in lxi-tools v2.4 the following change was introduced:
https://github.com/lxi-tools/lxi-tools/releases/tag/v2.4

So you must be trying to run some old scripts which have not been updated to use the new API.

Examples and doc have been updated:
https://github.com/lxi-tools/lxi-tools/blob/master/doc/lua-api.txt
https://github.com/lxi-tools/lxi-tools/tree/master/examples/lua

**Comment by MarkSupp** [comment]
On behalf of my father and I we can't thank you enough for your help! As a sidenote, it might also be a good idea to change the examples given in the Readme on the front page.

**Comment by lundmar** [comment]
You're welcome. Yes, I need to update the screenshots.
