### ISSUE TITLE
Siglent SPD1168X Test Report

### ISSUE THREAD

**Issue by MikeC96** [lxi-tools/lxi-tools#75]
Hello! I just tested with my Siglent SPD1168X. 

SCPI commands work great, however, discover does not work (similar to the SPD3303X).

Thanks so much for the work you're doing! 

If you'd like support with any additional testing for the SDP1168X, I'm happy to help, just let me know!

**Comment by lundmar** [comment]
Thanks for the report 👍🏻 

It looks like Siglent were a bit lazy with their SPD series of power supplies as they seem to only support SCPI commands. No screenshot, no discovery.

I've added your instrument to our list of tested instruments.
