### ISSUE TITLE
DS1074Z/DS1104Z working features

### ISSUE THREAD

**Issue by SillieWous** [lxi-tools/lxi-tools#77]
In the list of working features it lists "discovery" as working. Does that mean both via mDNS and LXI?
I am asking because I'm able to discover it via LXI, but not via mDNS. Could very well be  a network issue on my side though.

**Comment by lundmar** [comment]
It means one or the other or both.

If I remember correctly, the Rigol DS1000Z series does not feature mDNS discovery.

**Comment by SillieWous** [comment]
Hmm interesting. It does sort of seem to have the port open (but it is UDP, so not entirely sure).
But that does answer my question
