### ISSUE TITLE
Binary has undeclared dependency on libcairo and libgdk-pixbuf

### ISSUE THREAD

**Issue by janhenke** [lxi-tools/lxi-tools#87]
This was caught by a QA check in Gentoo ([Gentoo Bug 933182](https://bugs.gentoo.org/933182))

After building lxi-tools the binary has runtime dependency on libcairo and libgdk-pixbuf, but it never declares its dependency or linkage to either of these libraries in its build files.

If symbols from either of these libraries are used, they should be linked to explicitly.

**Comment by lundmar** [comment]
Fixed in bf0cf6b677b73a536a7c2aeab20107e26a7713e6
