### ISSUE TITLE
click-drag titlebar causes cursor and window to jump

### ISSUE THREAD

**Issue by mpictor** [lxi-tools/lxi-tools#88]
First, thanks for writing this!

I'm using the `nix` package of v2.7.
My desktop is mostly KDE, if that could make a difference.

If I click and drag on the titlebar, the cursor and window jump up and to the left.

It seems like it calculates the upper left corner of the left display and repositions the cursor (and window) halfway between the initial location and that corner - the distance moved grows smaller as the initial location approaches the upper left corner.

**Comment by lundmar** [comment]
Sounds like a bug in whatever terminal application you are using to run tio in.

Try a different terminal application like e.g. gnome-terminal.
