### ISSUE TITLE
Signed release of v2.8 like for v2.7?

### ISSUE THREAD

**Issue by robert-scheck** [lxi-tools/lxi-tools#98]
As of writing, there is no signed release of v2.8 available, like it is for v2.7:

 - So, https://github.com/lxi-tools/lxi-tools/releases/tag/v2.7 shows
   - `lxi-tools-2.7.tar.xz`,
   - `lxi-tools-2.7.tar.xz.asc`, and
   - `lxi-tools-2.7.tar.xz.sha256sum`,
 - but https://github.com/lxi-tools/lxi-tools/releases/tag/v2.8 does not.

Is this intended?

**Comment by robert-scheck** [comment]
Thank you for letting me know. Pushing a tag woke the Fedora mechanisms up ;-)

**Comment by lundmar** [comment]
Ha ha, sorry about that :D

**Comment by lundmar** [comment]
FYI - the release is now available.

**Comment by robert-scheck** [comment]
Thank you, v2.8 has been built for all active Fedora and EPEL releases.
